export type SearchQueryPayload = Record<string, unknown>;

export interface SearchQuery {
  name: string;
  payload: SearchQueryPayload;
}

const distanceQueries: SearchQuery[] = [
  {
    name: "anglais-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15234",
        libelle: "ANGLAIS",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "bilan-competences-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "CPF202",
        libelle: "BILAN DE COMPETENCES",
        type: "CERTIFICATION",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "vae-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "44591",
        libelle: "VALIDATION ACQUIS EXPERIENCE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "allemand-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15287",
        libelle: "ALLEMAND",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "comptable-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32663",
        libelle: "COMPTABLE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "permis-b-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "CPF206",
        libelle: "PERMIS B",
        type: "CERTIFICATION",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "sante-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "43454",
        libelle: "SANTE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "petite-enfance-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "44041",
        libelle: "PETITE ENFANCE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "caces-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31795",
        libelle: "CACES",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "immobilier-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42154",
        libelle: "IMMOBILIER",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "prothesiste-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "43484",
        libelle: "PROTHESISTE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "coiffure-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42050",
        libelle: "COIFFURE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "maintenance-industrielle-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31624",
        libelle: "MAINTENANCE INDUSTRIELLE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "reseau-social-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "46359",
        libelle: "RESEAU SOCIAL",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
  {
    name: "automatisation-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "24472",
        libelle: "AUTOMATISATION",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "chantier-btp-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "22274",
        libelle: "CHANTIER BTP",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "agriculteur-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "21054",
        libelle: "AGRICULTEUR",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "creation-entreprise-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32047",
        libelle: "CREATION ENTREPRISE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "management-equipe-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32154",
        libelle: "MANAGEMENT EQUIPE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
  {
    name: "psychologue-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "14454",
        libelle: "PSYCHOLOGUE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "estheticienne-cosmeticienne-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42032",
        libelle: "ESTHETICIENNE-COSMETICIENNE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "coach-sportif-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15436",
        libelle: "COACH SPORTIF",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
];

type CityConfig = {
  slug: string;
  name: string;
  postalCode: string;
  inseeCode: string;
  longitude: number;
  latitude: number;
};

const mixteCities: CityConfig[] = [
  {
    slug: "angers",
    name: "ANGERS",
    postalCode: "49000",
    inseeCode: "49007",
    longitude: -0.54503,
    latitude: 47.49149,
  },
  {
    slug: "avignon",
    name: "AVIGNON",
    postalCode: "84000",
    inseeCode: "84007",
    longitude: 4.841166,
    latitude: 43.93526,
  },
  {
    slug: "bordeaux",
    name: "BORDEAUX",
    postalCode: "33000",
    inseeCode: "33063",
    longitude: -0.573595,
    latitude: 44.857937,
  },
  {
    slug: "dijon",
    name: "DIJON",
    postalCode: "21000",
    inseeCode: "21231",
    longitude: 5.0375123,
    latitude: 47.32294,
  },
  {
    slug: "grenoble",
    name: "GRENOBLE",
    postalCode: "38000",
    inseeCode: "38185",
    longitude: 5.720799,
    latitude: 45.182156,
  },
  {
    slug: "lyon",
    name: "LYON",
    postalCode: "69000",
    inseeCode: "69123",
    longitude: 4.832079,
    latitude: 45.757774,
  },
  {
    slug: "lille",
    name: "LILLE",
    postalCode: "59000",
    inseeCode: "59350",
    longitude: 3.047087,
    latitude: 50.63192,
  },
  {
    slug: "marseille",
    name: "MARSEILLE",
    postalCode: "13000",
    inseeCode: "13055",
    longitude: 5.36978,
    latitude: 43.296482,
  },
  {
    slug: "montpellier",
    name: "MONTPELLIER",
    postalCode: "34000",
    inseeCode: "34172",
    longitude: 3.869198,
    latitude: 43.613087,
  },
  {
    slug: "toulouse",
    name: "TOULOUSE",
    postalCode: "31000",
    inseeCode: "31555",
    longitude: 1.4322938,
    latitude: 43.59597,
  },
  {
    slug: "toulon",
    name: "TOULON",
    postalCode: "83000",
    inseeCode: "83137",
    longitude: 5.9327564,
    latitude: 43.136402,
  },
  {
    slug: "tours",
    name: "TOURS",
    postalCode: "37000",
    inseeCode: "37261",
    longitude: 0.69629747,
    latitude: 47.397972,
  },
  {
    slug: "nantes",
    name: "NANTES",
    postalCode: "44000",
    inseeCode: "44109",
    longitude: -1.5478069,
    latitude: 47.23218,
  },
  {
    slug: "nice",
    name: "NICE",
    postalCode: "06000",
    inseeCode: "06088",
    longitude: 7.237529,
    latitude: 43.712227,
  },
  {
    slug: "paris",
    name: "PARIS",
    postalCode: "75000",
    inseeCode: "75056",
    longitude: 2.342562,
    latitude: 48.85653,
  },
  {
    slug: "rennes",
    name: "RENNES",
    postalCode: "35000",
    inseeCode: "35238",
    longitude: -1.6816379,
    latitude: 48.111637,
  },
  {
    slug: "strasbourg",
    name: "STRASBOURG",
    postalCode: "67000",
    inseeCode: "67482",
    longitude: 7.7676826,
    latitude: 48.57162,
  },
  {
    slug: "reims",
    name: "REIMS",
    postalCode: "51100",
    inseeCode: "51454",
    longitude: 4.031696,
    latitude: 49.258329,
  },
  {
    slug: "le-havre",
    name: "LE HAVRE",
    postalCode: "76600",
    inseeCode: "76351",
    longitude: 0.107929,
    latitude: 49.493802,
  },
  {
    slug: "saint-etienne",
    name: "SAINT-ETIENNE",
    postalCode: "42000",
    inseeCode: "42218",
    longitude: 4.387179,
    latitude: 45.439695,
  },
  {
    slug: "clermont-ferrand",
    name: "CLERMONT-FERRAND",
    postalCode: "63000",
    inseeCode: "63113",
    longitude: 3.087025,
    latitude: 45.777222,
  },
  {
    slug: "rouen",
    name: "ROUEN",
    postalCode: "76000",
    inseeCode: "76540",
    longitude: 1.099321,
    latitude: 49.443231,
  },
  {
    slug: "nimes",
    name: "NIMES",
    postalCode: "30000",
    inseeCode: "30189",
    longitude: 4.360054,
    latitude: 43.836699,
  },
  {
    slug: "orleans",
    name: "ORLEANS",
    postalCode: "45000",
    inseeCode: "45234",
    longitude: 1.909251,
    latitude: 47.902532,
  },
  {
    slug: "brest",
    name: "BREST",
    postalCode: "29200",
    inseeCode: "29019",
    longitude: -4.486076,
    latitude: 48.390394,
  },
  {
    slug: "caen",
    name: "CAEN",
    postalCode: "14000",
    inseeCode: "14118",
    longitude: -0.370679,
    latitude: 49.181086,
  },
  {
    slug: "nancy",
    name: "NANCY",
    postalCode: "54000",
    inseeCode: "54395",
    longitude: 6.184417,
    latitude: 48.692054,
  },
  {
    slug: "metz",
    name: "METZ",
    postalCode: "57000",
    inseeCode: "57463",
    longitude: 6.175715,
    latitude: 49.119308,
  },
  {
    slug: "perpignan",
    name: "PERPIGNAN",
    postalCode: "66000",
    inseeCode: "66136",
    longitude: 2.894833,
    latitude: 42.688659,
  },
  {
    slug: "amiens",
    name: "AMIENS",
    postalCode: "80000",
    inseeCode: "80021",
    longitude: 2.295694,
    latitude: 49.894067,
  },
  {
    slug: "limoges",
    name: "LIMOGES",
    postalCode: "87000",
    inseeCode: "87085",
    longitude: 1.261105,
    latitude: 45.833619,
  },
  {
    slug: "besancon",
    name: "BESANCON",
    postalCode: "25000",
    inseeCode: "25056",
    longitude: 6.024053,
    latitude: 47.237828,
  },
  {
    slug: "mulhouse",
    name: "MULHOUSE",
    postalCode: "68100",
    inseeCode: "68224",
    longitude: 7.335888,
    latitude: 47.750839,
  },
];

interface MixteTheme {
  slug: string;
  code: string;
  libelle: string;
  type: "FORMACODE" | "CERTIFICATION";
}

const mixteThemes: MixteTheme[] = [
  {
    slug: "bilan-competences",
    code: "CPF202",
    libelle: "BILAN DE COMPETENCES",
    type: "CERTIFICATION",
  },
  {
    slug: "developpeur-web",
    code: "31090",
    libelle: "DEVELOPPEUR WEB",
    type: "FORMACODE",
  },
  {
    slug: "anglais",
    code: "15234",
    libelle: "ANGLAIS",
    type: "FORMACODE",
  },
  {
    slug: "allemand",
    code: "15287",
    libelle: "ALLEMAND",
    type: "FORMACODE",
  },
  {
    slug: "espagnol",
    code: "15228",
    libelle: "ESPAGNOL",
    type: "FORMACODE",
  },
  {
    slug: "graphisme",
    code: "46072",
    libelle: "GRAPHISME",
    type: "FORMACODE",
  },
  {
    slug: "bureautique",
    code: "15052",
    libelle: "BUREAUTIQUE",
    type: "FORMACODE",
  },
  {
    slug: "secretaire",
    code: "35054",
    libelle: "SECRETAIRE",
    type: "FORMACODE",
  },
  {
    slug: "assistante-commerciale",
    code: "35028",
    libelle: "ASSISTANTE COMMERCIALE",
    type: "FORMACODE",
  },
  {
    slug: "logistique",
    code: "31845",
    libelle: "LOGISTIQUE",
    type: "FORMACODE",
  },
  {
    slug: "electricite",
    code: "24054",
    libelle: "ELECTRICITE",
    type: "FORMACODE",
  },
  {
    slug: "marketing",
    code: "34052",
    libelle: "MARKETING",
    type: "FORMACODE",
  },
  {
    slug: "cybersecurite",
    code: "31045",
    libelle: "CYBERSECURITE",
    type: "FORMACODE",
  },
  {
    slug: "gestionnaire-paie",
    code: "32688",
    libelle: "GESTIONNAIRE PAIE",
    type: "FORMACODE",
  },
  {
    slug: "informaticien",
    code: "31054",
    libelle: "INFORMATICIEN",
    type: "FORMACODE",
  },
  {
    slug: "handicap",
    code: "44024",
    libelle: "HANDICAP",
    type: "FORMACODE",
  },
  {
    slug: "permis-b",
    code: "CPF206",
    libelle: "PERMIS B",
    type: "CERTIFICATION",
  },
  {
    slug: "sante",
    code: "43454",
    libelle: "SANTE",
    type: "FORMACODE",
  },
  {
    slug: "petite-enfance",
    code: "44041",
    libelle: "PETITE ENFANCE",
    type: "FORMACODE",
  },
  {
    slug: "caces",
    code: "31795",
    libelle: "CACES",
    type: "FORMACODE",
  },
  {
    slug: "immobilier",
    code: "42154",
    libelle: "IMMOBILIER",
    type: "FORMACODE",
  },
  {
    slug: "prothesiste",
    code: "43484",
    libelle: "PROTHESISTE",
    type: "FORMACODE",
  },
  {
    slug: "coiffure",
    code: "42050",
    libelle: "COIFFURE",
    type: "FORMACODE",
  },
  {
    slug: "maintenance-industrielle",
    code: "31624",
    libelle: "MAINTENANCE INDUSTRIELLE",
    type: "FORMACODE",
  },
  {
    slug: "reseau-social",
    code: "46359",
    libelle: "RESEAU SOCIAL",
    type: "FORMACODE",
  },
  {
    slug: "automatisation",
    code: "24472",
    libelle: "AUTOMATISATION",
    type: "FORMACODE",
  },
  {
    slug: "chantier-btp",
    code: "22274",
    libelle: "CHANTIER BTP",
    type: "FORMACODE",
  },
  {
    slug: "agriculteur",
    code: "21054",
    libelle: "AGRICULTEUR",
    type: "FORMACODE",
  },
  {
    slug: "creation-entreprise",
    code: "32047",
    libelle: "CREATION ENTREPRISE",
    type: "FORMACODE",
  },
  {
    slug: "management-equipe",
    code: "32154",
    libelle: "MANAGEMENT EQUIPE",
    type: "FORMACODE",
  },
  {
    slug: "psychologue",
    code: "14454",
    libelle: "PSYCHOLOGUE",
    type: "FORMACODE",
  },
  {
    slug: "estheticienne-cosmeticienne",
    code: "42032",
    libelle: "ESTHETICIENNE-COSMETICIENNE",
    type: "FORMACODE",
  },
  {
    slug: "coach-sportif",
    code: "15436",
    libelle: "COACH SPORTIF",
    type: "FORMACODE",
  },
];

const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const createMixtePayload = (
  city: CityConfig,
  theme: MixteTheme
): SearchQueryPayload => ({
  ou: {
    modality: "EN_CENTRE_MIXTE",
    type: "CP",
    ville: {
      nom: city.name,
      codePostal: city.postalCode,
      codeInsee: city.inseeCode,
      coordonnee: {
        longitude: city.longitude,
        latitude: city.latitude,
      },
      eligibleCpf: true,
    },
  },
  debutPagination: 1,
  nombreOccurences: 10,
  contexteFormation: "ACTIVITE_PROFESSIONNELLE",
  nomOrganisme: null,
  conformiteReglementaire: null,
  endDate: null,
  startDate: null,
  evaluation: null,
  niveauSortie: null,
  minPrix: null,
  maxPrix: null,
  rythme: null,
  onlyWithAbondementsEligibles: null,
  durationHours: null,
  certifications: null,
  distance: "100",
  quoi: null,
  quoiReferentiel: {
    code: theme.code,
    libelle: theme.libelle,
    type: theme.type,
    publics: ["GD_PUBLIC"],
  },
});

const mixteQueries: SearchQuery[] = shuffleArray(mixteThemes).flatMap((theme) =>
  mixteCities.map((city) => ({
    name: `${theme.slug}-${city.slug}-mixte`,
    payload: createMixtePayload(city, theme),
  }))
);

export const searchQueries: SearchQuery[] = [
  ...distanceQueries,
  ...mixteQueries,
];
