export type SearchQueryPayload = Record<string, unknown>;

export interface SearchQuery {
  name: string;
  payload: SearchQueryPayload;
}

const distanceQueries: SearchQuery[] = [
  {
    name: "anglais-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15234",
        libelle: "ANGLAIS",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "bilan-competences-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "CPF202",
        libelle: "BILAN DE COMPETENCES",
        type: "CERTIFICATION",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "vae-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "44591",
        libelle: "VALIDATION ACQUIS EXPERIENCE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "allemand-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15287",
        libelle: "ALLEMAND",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "comptable-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32663",
        libelle: "COMPTABLE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "permis-b-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "CPF206",
        libelle: "PERMIS B",
        type: "CERTIFICATION",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "sante-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "43454",
        libelle: "SANTE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "petite-enfance-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "44041",
        libelle: "PETITE ENFANCE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "caces-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31795",
        libelle: "CACES",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "immobilier-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42154",
        libelle: "IMMOBILIER",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "prothesiste-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "43484",
        libelle: "PROTHESISTE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "coiffure-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42050",
        libelle: "COIFFURE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "maintenance-industrielle-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31624",
        libelle: "MAINTENANCE INDUSTRIELLE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "reseau-social-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "46359",
        libelle: "RESEAU SOCIAL",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
  {
    name: "automatisation-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "24472",
        libelle: "AUTOMATISATION",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "chantier-btp-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "22274",
        libelle: "CHANTIER BTP",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "agriculteur-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "21054",
        libelle: "AGRICULTEUR",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "creation-entreprise-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32047",
        libelle: "CREATION ENTREPRISE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "management-equipe-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32154",
        libelle: "MANAGEMENT EQUIPE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
  {
    name: "psychologue-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "14454",
        libelle: "PSYCHOLOGUE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "estheticienne-cosmeticienne-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "42032",
        libelle: "ESTHETICIENNE-COSMETICIENNE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "coach-sportif-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "15436",
        libelle: "COACH SPORTIF",
        type: "FORMACODE",
        publics: ["GD_PUBLIC", "ELU"],
      },
    },
  },
  {
    name: "seo-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "46336",
        libelle: "SEO - SEARCH ENGINE OPTIMIZATION",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "e-commerce-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "34530",
        libelle: "E-COMMERCE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "business-developer-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "34085",
        libelle: "BUSINESS DEVELOPER",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "chef-projet-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32135",
        libelle: "CHEF PROJET",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "assistante-de-vie-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "44028",
        libelle: "ASSISTANTE DE VIE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "informatique-systemes-information-numerique-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31054",
        libelle: "INFORMATIQUE - SYSTEMES D'INFORMATION ET NUMERIQUE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "conduite-projet-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "32135",
        libelle: "CONDUITE PROJET",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
  {
    name: "data-analyse-distance",
    payload: {
      ou: {
        modality: "A_DISTANCE",
        type: "CP",
      },
      debutPagination: 1,
      nombreOccurences: 10,
      contexteFormation: "ACTIVITE_PROFESSIONNELLE",
      nomOrganisme: null,
      endDate: null,
      startDate: null,
      evaluation: null,
      niveauSortie: null,
      minPrix: null,
      maxPrix: null,
      rythme: null,
      onlyWithAbondementsEligibles: null,
      durationHours: null,
      certifications: null,
      quoi: null,
      quoiReferentiel: {
        code: "31025",
        libelle: "DATA ANALYSE",
        type: "FORMACODE",
        publics: ["GD_PUBLIC"],
      },
    },
  },
];

type CityConfig = {
  slug: string;
  name: string;
  postalCode: string;
  inseeCode: string;
  longitude: number;
  latitude: number;
};

const mixteCities: CityConfig[] = [
  {
    slug: "paris",
    name: "PARIS",
    postalCode: "75000",
    inseeCode: "75056",
    longitude: 2.342562,
    latitude: 48.85653,
  },
];

interface MixteTheme {
  slug: string;
  code: string;
  libelle: string;
  type: "FORMACODE" | "CERTIFICATION";
}

const mixteThemes: MixteTheme[] = [
  {
    slug: "bilan-competences",
    code: "CPF202",
    libelle: "BILAN DE COMPETENCES",
    type: "CERTIFICATION",
  },
  {
    slug: "developpeur-web",
    code: "31090",
    libelle: "DEVELOPPEUR WEB",
    type: "FORMACODE",
  },
  {
    slug: "anglais",
    code: "15234",
    libelle: "ANGLAIS",
    type: "FORMACODE",
  },
  {
    slug: "allemand",
    code: "15287",
    libelle: "ALLEMAND",
    type: "FORMACODE",
  },
  {
    slug: "espagnol",
    code: "15228",
    libelle: "ESPAGNOL",
    type: "FORMACODE",
  },
  {
    slug: "massage-bien-etre",
    code: "43445",
    libelle: "MASSAGE BIEN-ETRE",
    type: "FORMACODE",
  },
  {
    slug: "marketing",
    code: "34052",
    libelle: "MARKETING",
    type: "FORMACODE",
  },
  {
    slug: "communication-vente",
    code: "34026",
    libelle: "COMMUNICATION VENTE",
    type: "FORMACODE",
  },
  {
    slug: "leadership",
    code: "32130",
    libelle: "LEADERSHIP",
    type: "FORMACODE",
  },
  {
    slug: "directrice-ressources-humaines",
    code: "33054",
    libelle: "DIRECTRICE RESSOURCES HUMAINES",
    type: "FORMACODE",
  },
  {
    slug: "art",
    code: "45054",
    libelle: "ART",
    type: "FORMACODE",
  },
  {
    slug: "decoratrice",
    code: "45040",
    libelle: "DECORATRICE",
    type: "FORMACODE",
  },
  {
    slug: "banque",
    code: "41062",
    libelle: "BANQUE",
    type: "FORMACODE",
  },
  {
    slug: "petite-enfance",
    code: "44041",
    libelle: "PETITE ENFANCE",
    type: "FORMACODE",
  },
  {
    slug: "puericultrice",
    code: "43439",
    libelle: "PUERICULTRICE",
    type: "FORMACODE",
  },
  {
    slug: "sante",
    code: "43454",
    libelle: "SANTE",
    type: "FORMACODE",
  },
  {
    slug: "service-a-la-personne",
    code: "42056",
    libelle: "SERVICE A LA PERSONNE",
    type: "FORMACODE",
  },
  {
    slug: "transport",
    code: "31854",
    libelle: "TRANSPORT",
    type: "FORMACODE",
  },
  {
    slug: "graphisme",
    code: "46072",
    libelle: "GRAPHISME",
    type: "FORMACODE",
  },
  {
    slug: "bureautique",
    code: "15052",
    libelle: "BUREAUTIQUE",
    type: "FORMACODE",
  },
  {
    slug: "secretaire",
    code: "35054",
    libelle: "SECRETAIRE",
    type: "FORMACODE",
  },
  {
    slug: "assistante-commerciale",
    code: "35028",
    libelle: "ASSISTANTE COMMERCIALE",
    type: "FORMACODE",
  },
  {
    slug: "logistique",
    code: "31845",
    libelle: "LOGISTIQUE",
    type: "FORMACODE",
  },
  {
    slug: "electricite",
    code: "24054",
    libelle: "ELECTRICITE",
    type: "FORMACODE",
  },
  {
    slug: "marketing",
    code: "34052",
    libelle: "MARKETING",
    type: "FORMACODE",
  },
  {
    slug: "cybersecurite",
    code: "31045",
    libelle: "CYBERSECURITE",
    type: "FORMACODE",
  },
  {
    slug: "gestionnaire-paie",
    code: "32688",
    libelle: "GESTIONNAIRE PAIE",
    type: "FORMACODE",
  },
  {
    slug: "informaticien",
    code: "31054",
    libelle: "INFORMATICIEN",
    type: "FORMACODE",
  },
  {
    slug: "handicap",
    code: "44024",
    libelle: "HANDICAP",
    type: "FORMACODE",
  },
  {
    slug: "permis-b",
    code: "CPF206",
    libelle: "PERMIS B",
    type: "CERTIFICATION",
  },
  {
    slug: "sante",
    code: "43454",
    libelle: "SANTE",
    type: "FORMACODE",
  },
  {
    slug: "petite-enfance",
    code: "44041",
    libelle: "PETITE ENFANCE",
    type: "FORMACODE",
  },
  {
    slug: "caces",
    code: "31795",
    libelle: "CACES",
    type: "FORMACODE",
  },
  {
    slug: "immobilier",
    code: "42154",
    libelle: "IMMOBILIER",
    type: "FORMACODE",
  },
  {
    slug: "prothesiste",
    code: "43484",
    libelle: "PROTHESISTE",
    type: "FORMACODE",
  },
  {
    slug: "coiffure",
    code: "42050",
    libelle: "COIFFURE",
    type: "FORMACODE",
  },
  {
    slug: "maintenance-industrielle",
    code: "31624",
    libelle: "MAINTENANCE INDUSTRIELLE",
    type: "FORMACODE",
  },
  {
    slug: "reseau-social",
    code: "46359",
    libelle: "RESEAU SOCIAL",
    type: "FORMACODE",
  },
  {
    slug: "automatisation",
    code: "24472",
    libelle: "AUTOMATISATION",
    type: "FORMACODE",
  },
  {
    slug: "chantier-btp",
    code: "22274",
    libelle: "CHANTIER BTP",
    type: "FORMACODE",
  },
  {
    slug: "agriculteur",
    code: "21054",
    libelle: "AGRICULTEUR",
    type: "FORMACODE",
  },
  {
    slug: "creation-entreprise",
    code: "32047",
    libelle: "CREATION ENTREPRISE",
    type: "FORMACODE",
  },
  {
    slug: "management-equipe",
    code: "32154",
    libelle: "MANAGEMENT EQUIPE",
    type: "FORMACODE",
  },
  {
    slug: "psychologue",
    code: "14454",
    libelle: "PSYCHOLOGUE",
    type: "FORMACODE",
  },
  {
    slug: "estheticienne-cosmeticienne",
    code: "42032",
    libelle: "ESTHETICIENNE-COSMETICIENNE",
    type: "FORMACODE",
  },
  {
    slug: "coach-sportif",
    code: "15436",
    libelle: "COACH SPORTIF",
    type: "FORMACODE",
  },
  {
    slug: "seo",
    code: "46336",
    libelle: "SEO - SEARCH ENGINE OPTIMIZATION",
    type: "FORMACODE",
  },
  {
    slug: "e-commerce",
    code: "34530",
    libelle: "E-COMMERCE",
    type: "FORMACODE",
  },
  {
    slug: "business-developer",
    code: "34085",
    libelle: "BUSINESS DEVELOPER",
    type: "FORMACODE",
  },
  {
    slug: "chef-projet",
    code: "32135",
    libelle: "CHEF PROJET",
    type: "FORMACODE",
  },
  {
    slug: "assistante-de-vie",
    code: "44028",
    libelle: "ASSISTANTE DE VIE",
    type: "FORMACODE",
  },
  {
    slug: "informatique-systemes-information-numerique",
    code: "31054",
    libelle: "INFORMATIQUE - SYSTEMES D'INFORMATION ET NUMERIQUE",
    type: "FORMACODE",
  },
  {
    slug: "conduite-projet",
    code: "32135",
    libelle: "CONDUITE PROJET",
    type: "FORMACODE",
  },
  {
    slug: "data-analyse",
    code: "31025",
    libelle: "DATA ANALYSE",
    type: "FORMACODE",
  },
  {
    slug: "animalerie",
    code: "42004",
    libelle: "ANIMALERIE",
    type: "FORMACODE",
  },
  {
    slug: "decorateur",
    code: "45040",
    libelle: "DECORATEUR",
    type: "FORMACODE",
  },
  {
    slug: "boulanger",
    code: "21539",
    libelle: "BOULANGER",
    type: "FORMACODE",
  },
  {
    slug: "patissier",
    code: "21528",
    libelle: "PATISSIER",
    type: "FORMACODE",
  },
  {
    slug: "cuisine",
    code: "42752",
    libelle: "CUISINE",
    type: "FORMACODE",
  },
];

const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const createMixtePayload = (
  city: CityConfig,
  theme: MixteTheme
): SearchQueryPayload => ({
  ou: {
    modality: "EN_CENTRE_MIXTE",
    type: "CP",
    ville: {
      nom: city.name,
      codePostal: city.postalCode,
      codeInsee: city.inseeCode,
      coordonnee: {
        longitude: city.longitude,
        latitude: city.latitude,
      },
      eligibleCpf: true,
    },
  },
  debutPagination: 1,
  nombreOccurences: 10,
  contexteFormation: "ACTIVITE_PROFESSIONNELLE",
  nomOrganisme: null,
  conformiteReglementaire: null,
  endDate: null,
  startDate: null,
  evaluation: null,
  niveauSortie: null,
  minPrix: null,
  maxPrix: null,
  rythme: null,
  onlyWithAbondementsEligibles: null,
  durationHours: null,
  certifications: null,
  distance: "50000",
  quoi: null,
  quoiReferentiel: {
    code: theme.code,
    libelle: theme.libelle,
    type: theme.type,
    publics: ["GD_PUBLIC"],
  },
});

const mixteQueries: SearchQuery[] = shuffleArray(mixteThemes).flatMap((theme) =>
  mixteCities
    .filter((city) => city.slug === "paris")
    .map((city) => ({
      name: `${theme.slug}-${city.slug}-mixte`,
      payload: createMixtePayload(city, theme),
    }))
);

export const searchQueries: SearchQuery[] = [
  ...distanceQueries,
  ...mixteQueries,
];
